api_platform:
    formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    error_formats:
        jsonproblem: [ 'application/problem+json' ]
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        versions: [3]
